version: '3.8'

services:
  redis_queue:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my_network

  spring-app:
    image: ztyle
    environment:
      GCS_BUCKET: ${버킷명}
      GCS_CREDENTIALS: ${프로젝트 권한키}
      GCS_PROJECT_ID: ${프로젝트 ID}
      SOURCE_MYSQL_URL: ${DB IP}
      SOURCE_MYSQL_USERNAME: ${DB 유저명}
      SOURCE_MYSQL_PASSWORD: ${DB 패스워드}
      SOURCE_REDIS_URL: redis_queue
      SOURCE_REDIS_PORT: 6379
      SPRING_PROFILE: ${프로필}
    depends_on:
      - redis_queue
    ports:
      - "8070:8080"    
    networks:
      - my_network
    
  tshirts-server:
    build:
      context: ./ml
      dockerfile: tshirts_docker
    ports:
      - "5000:5000"   
    networks:
      - my_network

  pants-server:
    build:
      context: ./ml
      dockerfile: pants_docker
    ports:
      - "5001:5001"
    networks:
      - my_network

  hat-server:
    build:
      context: ./ml
      dockerfile: hat_docker
    ports:
      - "5002:5002"   
    networks:
      - my_network

  skirt-server:
    build:
      context: ./ml
      dockerfile: skirt_docker
    ports:
      - "5003:5003"   
    networks:
      - my_network            

networks:
  my_network: