spring:
  datasource:
    url: ${SOURCE_MYSQL_URL}
    username: ${SOURCE_MYSQL_USERNAME}
    password: ${SOURCE_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  sql:
    init:
      mode: always
      data-locations: classpath:db/init.sql, classpath:db/data.sql
  cloud:
    gcp:
      storage:
        credentials:
          location: ${GCS_CREDENTIALS}
        project-id: ${GCS_PROJECT_ID}
        bucket: ${GCS_BUCKET}
  redis:
    data:
      host: ${SOURCE_REDIS_URL}
      port: ${SOURCE_REDIS_PORT}

worker:
  uri:
    tshirts-server: "http://tshirts-server:5000"
    pants-server: "http://pants-server:5001"
    hat-server: "http://hat-server:5002"
    skirt-server: "http://skirt-server:5003"

logging:
  config: classpath:log4j2-develop.yml