spring:
  datasource:
    url: ${SOURCE_MYSQL_URL}
    username: ${SOURCE_MYSQL_USERNAME}
    password: ${SOURCE_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  cloud:
    gcp:
      storage:
        credentials:
          location: ${GCS_CREDENTIALS}
        project-id: ${GCS_PROJECT_ID}
        bucket: ${GCS_BUCKET}