name: ci
on:
  pull_request:
    types: [opened, synchronize]
    branches: [develop, main]
    paths:
    - 'backend/**'
    - '.github/**'

defaults:
  run:
    working-directory: backend  

permissions:
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Repository를 가져온다
      uses: actions/checkout@v4

    - name: JDK 버전 17을 설치한다
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: gradle 의존성을 캐싱한다
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: gradlew 실행 권한을 부여한다
      run: chmod +x gradlew

    - name: gradle 빌드 테스트를 한다
      run: ./gradlew build

    - name: 테스트 코드 실행 결과 리포트를 작성한다
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: backend/build/test-results/test/TEST-*.xml    

    - name: 실패한 테스트를 PR 코멘트로 등록한다
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        report_paths: backend/build/test-results/test/TEST-*.xml